---
title: "R2 analysis"
author: "Abby Lewis"
date: "9/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plotly)
library(ggpubr)
```

Load/prepare data
```{r}
all <- read.csv("complete_dataset.csv")
all$R2_possible <- as.numeric(all$R2_possible)

all <- read.csv("complete_dataset.csv")
all$RMSE <- as.numeric(grepl("rmse|root mean squared error|root mean square error",tolower(all$Eval_metrics)))
sum(all$RMSE)
all$CRPS <- as.numeric(grepl("crps|continuous ranked probability score",tolower(all$Eval_metrics)))
sum(all$CRPS)
all$MAE <- as.numeric(grepl("mae|mean absolute error",tolower(all$Eval_metrics)))
sum(all$MAE)
#write.csv(all[all$RMSE == 1,],"rmse_analysis.csv",row.names = F)

using_r2 = all%>%
  filter(R2_possible == 1)
#r2_found <- read.csv("R2 analysis_04Nov20.csv")%>%
#  select(Title, R2_value, Notes)
#r2_second_attempt <- left_join(using_r2, r2_found)%>%
#  arrange(is.na(R2_value))
#write.csv(r2_second_attempt, "r2_second_attempt.csv", row.names = F)
r2s <- read.csv("r2_second_attempt.csv")%>%
  select(Title, R2_value, Notes, Site_or_year_group, Model_group, Modifications.needed, Var)
incorporating_gg_changes <- left_join(using_r2, r2s)
write.csv(incorporating_gg_changes,"r2_second_attempt.csv",row.names = F)

r2s<-read.csv("r2_second_attempt.csv")
r2s$Horiz_days[grepl("horiz",r2s$Modifications.needed, ignore.case = T)] <- as.numeric(gsub(".*horiz","",r2s$Modifications.needed[grepl("horiz",r2s$Modifications.needed, ignore.case = T)], ignore.case = T))
r2s$Var[is.na(r2s$Var)|nchar(r2s$Var)==0]<-r2s$Vars_ident[is.na(r2s$Var)|nchar(r2s$Var)==0]

#rmse<- read.csv("rmse_analysis.csv")
#rmse$Horiz_days[grepl("horiz",rmse$Modifications.needed, ignore.case = T)] <- as.numeric(gsub(".*horiz","",rmse$Modifications.needed[grepl("horiz",rmse$Modifications.needed, ignore.case = T)], ignore.case = T))
#rmse$Var[nchar(rmse$Var)==0]<-rmse$Vars_ident[nchar(rmse$Var)==0]
#chl_rmse = rmse[grepl("chl-a", rmse$Var, ignore.case  =T),]
#chl_rmse%>%
#  ggplot(aes(x = as.numeric(Horiz_days), y = RMSE_value))+
#  geom_point()

#### SHOULD DIFFERENT MODELS IN THE SAME PAPER BE COUNTED AS THE SAME OR DIFFERENT


r2s <- r2s%>%
  group_by_at(setdiff(names(r2s), c("Notes","R2_value","Site_or_year_group")))%>% #"Site_or_year_group","Model_group"
  summarize(R2_value = mean(as.numeric(R2_value),na.rm = T))%>%
  filter(!is.na(as.numeric(R2_value)))

r2s$Chla <- 0
r2s$Chla[grepl("chl",r2s$Var, ignore.case = T)]<-1

r2s$Fish <- 0
r2s$Fish[grepl("anchovy|mackarel|sardine|bonito|hake|fish|bluefin",r2s$Var, ignore.case = T)]<-1

r2s$Phyto <- 0
r2s$Phyto[grepl("cyano|oscillatoria|asterionella|desmus|anabena|aphaniz|microcyst|synecho|cyclo|stephanodiscus|raciborskii|circinale",r2s$Var, ignore.case = T)]<-1

r2s$Pollen <- 0
r2s$Pollen[grepl("pollen",r2s$Var, ignore.case = T)]<-1

r2s$Plants <- 0
r2s$Plants[grepl("corn|soybeans|rice|NDVI|evapotrans",r2s$Var, ignore.case = T)]<-1

r2s$ET <- 0
r2s$ET[grepl("evapotrans",r2s$Var, ignore.case = T)]<-1

r2s$Bird <- 0
r2s$Bird[grepl("turkey|bird|grouse|capercaill|grouse",r2s$Var, ignore.case = T)]<-1

r2s$OtherAnimal <- 0
r2s$OtherAnimal[grepl("porpoise|lobster|lolignid|ommastrephids|species",r2s$Var, ignore.case = T)]<-1

r2s$first <- as.numeric(as.factor(r2s$Title))

test = r2s%>%
  mutate(R2_value = as.numeric(R2_value))%>%
  filter(!is.na(R2_value))
length(unique(test$Title))
length(unique(all$Title[all$Forecast_eval_shown == "1"]))
56/135
46/135
27/135
```

Figure for paper
```{r}
r2s = r2s%>%
  filter(!is.na(as.numeric(Horiz_days)))

c = r2s%>%
  filter(Chla ==1,
         as.numeric(Horiz_days) <8)%>%
  ggplot(aes(x = as.numeric(Horiz_days), y = as.numeric(R2_value)))+
  geom_boxplot(aes(group = Horiz_days),outlier.shape = NA)+
  geom_jitter(aes(color = as.factor(first)),width = 0.1,size = 0.9)+
  xlab("Horiz (days)")+
  ylab("R2 value")+
  labs(color = "ID")+
  labs(title = "Chlorophyll", subtitle = "(n = 8)")+
  ylim(0,1)+
  theme_light()+
  theme(legend.position = "none")
  
p = r2s%>%
  filter(Pollen == 1,
         as.numeric(Horiz_days) <8)%>%
  ggplot(aes(x = as.numeric(Horiz_days), y = as.numeric(R2_value)))+
  geom_boxplot(aes(group = Horiz_days),outlier.shape = NA)+
  geom_jitter(aes(color = as.factor(first)),width = 0.1, size = 0.9)+
  labs(title = "Pollen", subtitle = "(n = 3)")+
  xlab("Horiz (days)")+
  labs(color = "ID")+
  ylim(0,1)+
  theme_light()+
  theme(axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "none")

e = r2s%>%
  filter(ET == 1,
         as.numeric(Horiz_days) <8)%>%
  ggplot(aes(x = as.numeric(Horiz_days), y = as.numeric(R2_value)))+
  geom_boxplot(aes(group = Horiz_days),outlier.shape = NA)+
  geom_jitter(aes(color = as.factor(first)),width = 0.1, size = 0.9)+
  labs(title = "Evapotranspiration", subtitle = "(n = 10)")+
  ylab("R2")+
  xlab("Horiz (days)")+
  labs(color = "ID")+
  ylim(0,1)+
  theme_light()+
  theme(axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "none")

phy = r2s%>%
  filter(Phyto ==1,
         as.numeric(Horiz_days) <8)%>%
  ggplot(aes(x = as.numeric(Horiz_days), y = as.numeric(R2_value)))+
  geom_boxplot(aes(group = Horiz_days),outlier.shape = NA)+
  geom_jitter(aes(color = as.factor(first)),width = 0.1,size = 0.9)+
  xlab("Horiz (days)")+
  ylab("R2 value")+
  labs(color = "ID")+
  labs(title = "Phytoplankton", subtitle = "(n = 8)")+
  ylim(0,1)+
  theme_light()+
  theme(axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.y = element_blank(),
        legend.position = "none")

ggarrange(c,phy,p,e, nrow = 1, widths = c(1.2,1,1,1))
jpeg("R2_compare.jpg",width = 8,height = 4,units = "in",res = 300)
ggarrange(c,phy,p,e, nrow = 1, widths = c(1.2,1,1,1))
dev.off()

#Tried to do breakpoint analysis but there is not enough data

stats = r2s%>%
  pivot_longer(c(Chla,Phyto,ET,Pollen))%>%
  filter(name %in% c("Chla","Phyto","ET","Pollen"),
         value == 1,
         Horiz_days<8)%>%
  mutate(Horiz_days = as.numeric(Horiz_days))

stats2 = r2s%>%
  filter(Horiz_days<8,
         Chla ==1|Phyto==1|ET==1|Pollen==1)%>%
  mutate(Horiz_days = as.numeric(Horiz_days))
summary(stats2)

medians = r2s%>%
  mutate(Horiz_days = as.numeric(Horiz_days))%>%
  pivot_longer(c(Chla,Phyto,ET,Pollen))%>%
  filter(name %in% c("Chla","Phyto","ET","Pollen"),
         value == 1,
         Horiz_days<8)%>%
  group_by(name,Horiz_days)%>%
  summarize(median = median(R2_value))

all = medians%>%
  ggplot(aes(x=Horiz_days,y=median, color = name))+
  geom_line()+
  theme_light()+
  xlab("Horiz (days")+
  ylim(0,1)+
  ylab("Median R2")+
  theme(axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.y = element_blank())+
  guides(col = guide_legend(ncol = 2,keyheight = .9))+
  theme(legend.position = "top",
        legend.title = element_blank(),
        legend.margin = margin(-1,-3,-3,-3,unit = "pt"))

jpeg("R2_compare2.jpg",width = 9,height = 4,units = "in",res = 300)
ggarrange(c,phy,p,e,all, nrow = 1, widths = c(1.25,1,1,1,1))
dev.off()
ggarrange(c,phy,p,e,all, nrow = 1, widths = c(1.2,1,1,1,1.2))

#an = aov(lm(R2_value~name*Horiz_days, data = stats))
library(quantreg)
stats = stats%>%
  filter(Horiz_days<=7)
model = rq(R2_value~name*Horiz_days, data = stats, tau = 0.5)
summary(model, se = "boot", bsmethod= "wild") #Can also try xy, but "wild" is justified by heteroskedasticity of chla

#summary(lm(R2_value~name+name:Horiz_days, data = stats))
#summary(lm(R2_value~name*Horiz_days, data = stats))
#model = lm(R2_value~name*Horiz_days, data = stats)
et = predict(model,data.frame(name=rep("ET",7),Horiz_days = 1:7))
chla = predict(model,data.frame(name=rep("Chla",7),Horiz_days = 1:7))
phyto = predict(model,data.frame(name=rep("Phyto",7),Horiz_days = 1:7))
pollen = predict(model,data.frame(name=rep("Pollen",7),Horiz_days = 1:7))

all2 = data.frame(horiz = 1:7,ET = et,Chl = chla,Phyto = phyto,Pollen = pollen)%>%
  pivot_longer(2:5)%>%
  ggplot(aes(x = horiz, y = value, color = name))+
  geom_line()+
  theme_light()+
  xlab("Horiz (days")+
  ylim(0,1)+
  ylab("Median R2")+
  theme(axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        axis.ticks.y = element_blank())+
  guides(col = guide_legend(ncol = 2,keyheight = .9))+
  theme(legend.position = "top",
        legend.title = element_blank(),
        legend.margin = margin(-1,-3,-3,-3,unit = "pt"))
jpeg("R2_with_indicators.jpg",res = 300, width = 9, height = 4, units = "in")
ggarrange(c,phy,p,e,all2, nrow = 1, widths = c(1.25,1,1,1,1))
dev.off()
ggarrange(c,phy,p,e,all2, nrow = 1, widths = c(1.25,1,1,1,1))
```

Other visualizations
```{r}
r2_plot = r2s%>%
  ggplot(aes(x = as.numeric(Horiz_days), y = as.numeric(R2_value)))+
  geom_point()+
  xlim(0,7)
ggplotly(r2_plot)

r2s%>%
  filter(Phyto ==1|Chla == 1)%>%
  ggplot(aes(x = as.numeric(Horiz_days), y = as.numeric(R2_value)))+
  geom_point(aes(color = as.factor(Met_covar_yn)))+
  xlim(0,10)+
  geom_smooth()+
  xlab("Horiz (days)")+
  ylab("R2 value")+
  labs(color = "Meteorological \ncovariates")+
  ggtitle("Phytoplankton forecast performance")

r2s%>%
  filter(Fish == 1)%>%
  ggplot(aes(x = as.numeric(Horiz_days), y = as.numeric(R2_value), color = as.factor(first)))+
  geom_point()+
  ggtitle("Fish")

r2s%>%
  filter(Pollen == 1)%>%
  ggplot(aes(x = as.numeric(Horiz_days), y = as.numeric(R2_value), color = as.factor(first)))+
  geom_point()+
  ggtitle("Pollen")


plants =r2s%>%
  filter(Plants == 1)%>%
  ggplot(aes(x = as.numeric(Horiz_days), y = as.numeric(R2_value), color = as.factor(Var)))+
  geom_point()+
  xlim(0,7)+
  ggtitle("Plants")
ggplotly(plants)

r2s%>%
  filter(OtherAnimal == 1)%>%
  ggplot(aes(x = as.numeric(Horiz_days), y = as.numeric(R2_value), color = as.factor(first)))+
  geom_point()+
  ggtitle("Other animals")

r2s%>%
  filter(Bird == 1)%>%
  ggplot(aes(x = as.numeric(Horiz_days), y = as.numeric(R2_value), color = as.factor(first)))+
  geom_point()+
  ggtitle("Birds")


r2s$Automated_bin <- 0
r2s$Automated_bin[r2s$Automated_yn %in% c("At least one data stream","Yes all data streams")]<-1
r2s$Proc_based <- 0
r2s$Proc_based[grepl("process-based",r2s$Model_type, ignore.case = T)]<-1

bar <- r2s%>%
  ungroup()%>%
  mutate(Uncert_yn = as.numeric(Uncert_category %in% c("data_driven", "propagates", "assimilates")),
         Coauthors_nonAc = as.numeric(Coauthors_nonAc > 0))%>%
    select(Uncert_yn,
         Null_yn,
         Forecast_eval_shown,
         Iterative_yn,
         Archiving_yn,
         End_user_yn,
         Proc_based,
         Automated_bin,
         Coauthors_nonAc,
         Multiple_approaches_yn,
         R2_value,
         Title)

bar%>%
  pivot_longer(seq(1,ncol(bar)-2))%>%
  group_by(name, value)%>%
  summarize(mean = mean(R2_value, na.rm = T),
            sd = sd(R2_value, na.rm = T),
            n = n(),
            n_papers = length(unique(Title)))%>%
  ggplot(aes(x = name, y = mean, fill = as.factor(value),group = as.factor(value)))+
  geom_bar(stat = "identity", position = "dodge", show.legend = F)+
  scale_x_discrete(breaks = c("Uncert_yn","Iterative_yn","End_user_yn","Null_yn","Archiving_yn","Forecast_eval_shown", "Automated_bin","Coauthors_nonAc","Multiple_approaches_yn","Proc_based"), labels = c("Data-driven \nuncertainty", "Iterative \nforecasts","End user \nspecified","Null model \ncomparison","Forecast \narchiving","Forecast \nevaluation \nin paper", "Workflow \nAutomation","Coauthor \nfrom outside \nacademia","Multiple \napproaches \ncompared","Process-based \nmodel"))+
  geom_errorbar(aes(ymin = mean-sd, ymax = mean+sd), position = "dodge")+
  geom_text(aes(label = n_papers, y = 0), position = position_dodge(0.9), vjust = -0.5)

anova(lm(bar$R2_value~bar$Iterative_yn+bar$Multiple_approaches_yn+bar$Coauthors_nonAc))

```

```{r}
r2 = read.csv("R2 Analysis_prelim.csv")

r2%>%
  mutate(R2_value = as.numeric(R2_value))%>%
  mutate(Horiz_days = as.numeric(Horiz_days))%>%
  ggplot(aes(x = Horiz_days, y = R2_value))+
  geom_point()+
  xlim(0,10)

r2%>%
  mutate(R2_value = as.numeric(R2_value))%>%
  mutate(Horiz_days = as.numeric(Horiz_days))%>%
  ggplot(aes(x = Class, y = R2_value))+
  geom_boxplot()

r2%>%
  mutate(R2_value = as.numeric(R2_value))%>%
  ggplot(aes(x = , y = R2_value))+
  geom_boxplot()

hist(as.numeric(r2$R2_value))

```
