---
title: "R Notebook"
output: html_notebook
---

Original abstract screening results
```{r}
library(VennDiagram)
library(tidyverse)
library(readxl)

#Load data
data<-read.csv("../Data/second_review_complete.csv", row.names = NULL)
data$Forecast[data$Forecast == "0?"]<-0
class(data$Forecast)<-"numeric"

#Add in papers that were found later
found <- read.csv("../Data/papers_to_find_edited.csv")
data2 <- data%>%
  full_join(found, by = c("TI", "DI","AB","AU","PY","DT","Reviewer", "Comment","SecondReviewer"))
#Replace evaluation with new information from found papers
data2[!is.na(data2$Found.)& data2$Found. == 1,c("NearTerm.x","Ecological.x","Forecast.x")]<-data2[!is.na(data2$Found.)& data2$Found. == 1,c("NearTerm.y","Ecological.y","Forecast.y")]
data <- data2%>%
  rename(Forecast = Forecast.x, NearTerm = NearTerm.x, Ecological = Ecological.x)
data$Forecast[!is.na(data$Only.Space.x)]<-0 #Forecasts that are only in space (not time) are not included as forecasts in this analysis

data1 <- read_csv("../Data/savedrecs_001_500.csv") #Load full data to filter out papers not published in English
data2 <- read_csv("../Data/savedrecs_501_1000.csv")
data3 <- read_csv("../Data/savedrecs_1001_1500.csv")
data4 <- read_csv("../Data/savedrecs_1501_2000.csv")
data5 <- read_csv("../Data/savedrecs_2001_2500.csv")
data6 <- read_csv("../Data/savedrecs_2501_2956.csv")
data_full <- data1%>% select(TI, LA, DT)%>%
  full_join(data2%>%  select(TI, LA, DT))%>%
  full_join(data3%>%  select(TI, LA, DT))%>%
  full_join(data4%>%  select(TI, LA, DT))%>%
  full_join(data5%>%  select(TI, LA, DT))%>%
  full_join(data6%>%  select(TI, LA, DT))%>%
  filter(LA == "English", #Select only papers published in English
         DT %in% c("Article","Article; Book Chapter","Article; Data Paper","Article; Early Access","Article; Proceedings Paper","Proceedings Paper"))

for_EDI = data%>%
  left_join(data_full, by = "TI")%>%
  filter(LA.y == "English", #Select only papers published in English
         DT.y %in% c("Article","Article; Book Chapter","Article; Data Paper","Article; Early Access","Article; Proceedings Paper","Proceedings Paper"))%>% #Select only articles and proceedings papers
  mutate(Round = 1) %>%
  select(TI,DI,AU,PY,Round,NearTerm, Ecological, Forecast) #Format for EDI

for_EDI = for_EDI[!duplicated(for_EDI$TI),]
write.csv(for_EDI, "../Data/original_abstract_review_papers_EDI.csv", row.names = F)
```

Citing/ed papers
```{r}
#Load data
cited_ing_with_journal <- read_csv("../Data/cited_ing_comb_second_review_finished.csv")
#Load found papers
found <- read_csv("../Data/cited_ing_papers_to_find_edited.csv")

#Join datasets
data2 <- cited_ing_with_journal%>%
  full_join(found, by = colnames(cited_ing_with_journal)[!colnames(cited_ing_with_journal) %in% c("X1","NearTerm","Ecological","Forecast","PaperUnavailable", "SecondComment")])
#Add in information from found papers
data2[!is.na(data2$PaperUnavailable.y)& data2$PaperUnavailable.y == 0,c("NearTerm.x","Ecological.x","Forecast.x")]<-data2[!is.na(data2$PaperUnavailable.y)& data2$PaperUnavailable.y == 0,c("NearTerm.y","Ecological.y","Forecast.y")]
data <- data2%>%
  rename(Forecast = Forecast.x, NearTerm = NearTerm.x, Ecological = Ecological.x)
data$Forecast[!is.na(data$Only.Space.x)]<-0 #Forecasts that are only in space (not time) are not included as forecasts in this analysis
for_EDI_citing_ed = data%>%
  select(TI,DI,AU,PY,NearTerm, Ecological, Forecast)%>%
  filter(!TI %in% c("Development of a Oak Pollen Emission and Transport Modeling Framework in South Korea", "Expertise for forecasting cotton production in Western Africa: a solution to emerging climate uncertainty?", "Improvement and Evaluation of Emission Formulas in UM-CMAQ-Pollen Model", "FORECAST OF A RED TIDE OCCURRENCE IN THE NORTHERN PART OF HIROSHIMA BAY .2. PREDICTION OF RED TIDE OCCURRENCE BY MEANS OF MULTIPLE LINEAR-REGRESSION MODEL")) #These are all not in English

write.csv(for_EDI_citing_ed, "../Data/cting_ed_abstract_review_papers_EDI.csv", row.names = F)
 
for_EDI_final = for_EDI%>%
  full_join(for_EDI_citing_ed %>% mutate(Round = 2))%>%
  arrange(PY,TI)%>%
  rename(Title = TI,
         Year = PY,
         doi = DI,
         Authors = AU)
for_EDI_final$NearTerm[for_EDI_final$Forecast==0]<-NA

for_EDI_final$NearTerm[is.na(for_EDI_final$NearTerm)&for_EDI_final$Forecast==1]<-0

write.csv(for_EDI_final, "../Data/abstract_review_all_papers_EDI.csv", row.names = F)
```

```{r}
reviewed = read.csv("../Data/abstract_review_all_papers_EDI.csv")%>%
  filter(NearTerm==1&Ecological==1&Forecast ==1)
final = read.csv("../Data/complete_dataset_with_source.csv")
lost = reviewed[!reviewed$Title%in%final$Title,]
write.csv(lost,"../Data/papers_removed_matrix_review.csv")
```


Calculating the number of cited and citing papers
```{r}
second <- read.csv("../Data/second_review_complete.csv")
citing <- read_csv("../Data/papers_citing_forecasts_full.csv")
citing_new <- citing %>%
  filter(LA == "English",
         DT %in% c("Article", "Article; Book Chapter", "Article; Proceedings Paper","Article; Early Access","Article; Proceedings Paper","Proceedings Paper"))
citing_new <- citing_new[!citing_new$TI %in% second$TI,]
379-271 #number of duplicates

cited<- read_csv("../Data/referenced_papers_forecasts.csv")
cited_new <- cited %>%
  filter(LA == "English",
         DT %in% c("Article", "Article; Proceedings Paper","Proceedings Paper"))
cited_new <- cited_new[!cited_new$TI %in% second$TI,]
#summary(as.factor(cited_new$DT))
306-214 #number of duplicates
#plus four found late

data3 <- read_csv("../Data/citing_ed_foundLate.csv")%>%
  rename(TI="Article Title",
         SO = "Source Title",
         LA = "Language")

og_titles = unique(c(citing_new$TI[!citing_new$TI %in% second$TI],cited_new$TI[!cited_new$TI %in% second$TI], data3$TI))
```